---
name: letsencrypt
director_uuid: 63ddb6a6-d6fe-40e1-b16b-2ff6b2034c79

releases:
- name: letsencrypt
  version: latest

networks:
- name: default
  type: manual
  subnets:
  - range: 10.244.0.0/24
    static: [10.244.0.88]

resource_pools:
- name: default
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  network: default
  cloud_properties: {}

compilation:
  workers: 2
  network: default
  cloud_properties: {}

update:
  canaries: 1
  canary_watch_time: 60000
  update_watch_time: 60000
  max_in_flight: 2

jobs:
- name: letsencrypt
  templates:
  - name: letsencrypt
  instances: 1
  resource_pool: default
  networks:
  - name: default
    static_ips: [10.244.0.88]
